#!/bin/bash
clear
echo '


     .─────────────────────────────────────────────────────────────.
     .                                                             .
     .                                                             .
     .              Введите размер Свапфайла                       .
     .                                                             .
     .             только цифру- 1 = 1гигабайту                    .
     .                                                             .
     ──────────────────────────────────────────────────────────────
'
read -p "
                -> Введите цифру : " size

sudo touch /home/swapfile
sudo chattr +C /home/swapfile
sudo fallocate --length ${size}GiB /home/swapfile
sudo chown root /home/swapfile
sudo chmod 600 /home/swapfile
sudo mkswap /home/swapfile
sudo swapon /home/swapfile
su root -c 'echo "/home/swapfile                           none            swap    defaults,pri=100         0 0" >> /etc/fstab'
echo '


     .─────────────────────────────────────────────────────────────.
     .                                                             .
     .                                                             .
     .              Готово , перезагрузите ПК                      .
     .                                                             .
     ──────────────────────────────────────────────────────────────
'
